import { IMAGES } from "@/lib/constants/images";
import { slugify } from "@/lib/utils";

const P = IMAGES.products;

/** Exact product slug → catalog image (name-accurate) */
const SLUG_IMAGE_MAP: Record<string, string> = {
  // Polo shirts — each design gets a distinct, name-matching photo
  "classic-pique-polo-shirt": P.polo,
  "performance-dry-fit-polo": P.poloMesh,
  "long-sleeve-pique-polo": P.poloLongSleeve,
  "striped-summer-polo": P.poloStriped,
  "executive-solid-polo": P.polo,
  "burgundy-club-polo": P.poloBurgundy,
  "sand-beige-resort-polo": P.poloBeige,
  "contrast-collar-polo": P.poloContrast,
  "tipped-cuff-fashion-polo": P.poloTipped,
  "mesh-panel-sports-polo": P.poloMesh,
  "rugby-stripe-polo": P.poloRugby,
  "pocket-detail-polo": P.poloPocket,
  "mercerized-cotton-polo": P.poloWhite,
  "eco-recycled-polo": P.poloOlive,
  "zip-neck-polo": P.poloZip,
  "henley-collar-polo": P.poloGrey,
  "slim-fit-corporate-polo": P.poloGrey,
  "relaxed-resort-polo": P.poloBeige,
  "golf-tour-performance-polo": P.poloOlive,
  "tennis-club-polo": P.poloWhite,
  "hospitality-uniform-polo": P.polo,
  "school-team-polo": P.poloColorblock,
  "fashion-colorblock-polo": P.poloColorblock,
  "premium-pearl-button-polo": P.poloWhite,
  "lightweight-travel-polo": P.poloBeige,
  "winter-thermal-polo": P.poloLongSleeve,
  "womens-fit-polo": P.poloWhite,
  "big-tall-polo": P.polo,
  "youth-team-polo": P.poloColorblock,
  "custom-embroidery-polo": P.poloGrey,

  // T-shirts
  "premium-cotton-crew-neck-tee": P.tshirt,
  "oversized-streetwear-tee": P.streetwearTee,
  "performance-moisture-wick-tee": P.performanceTee,
  "classic-v-neck-cotton-tee": P.vneckTee,
  "gold-accent-logo-tee": P.teeRed,
  "heavyweight-box-tee": P.streetwearTee,
  "slim-fit-essential-tee": P.tshirt,
  "gold-metallic-print-tee": P.teeRed,
  "forest-green-work-tee": P.performanceTee,
  "longline-drop-hem-tee": P.streetwearTee,
  "ringer-contrast-collar-tee": P.teeStack,
  "pocket-utility-tee": P.streetwearTee,
  "organic-cotton-basic-tee": P.tshirt,
  "tri-blend-fashion-tee": P.teeStack,
  "henley-button-placket-tee": P.teeStack,
  "raglan-baseball-tee": P.teeStack,
  "tie-dye-festival-tee": P.teeRed,
  "camo-print-military-tee": P.streetwearTee,
  "striped-breton-tee": P.teeStack,
  "curved-hem-fashion-tee": P.tshirt,
  "muscle-fit-gym-tee": P.performanceTee,
  "relaxed-fit-weekend-tee": P.teeStack,
  "embroidery-panel-tee": P.tshirt,
  "neon-performance-tee": P.teeRed,
  "vintage-wash-faded-tee": P.teeStack,
  "crop-length-fashion-tee": P.tshirt,
  "tall-fit-extended-tee": P.streetwearTee,
  "kids-youth-basic-tee": P.tshirt,
  "unisex-festival-tee": P.teeRed,
  "corporate-uniform-tee": P.tshirt,

  // Hoodies
  "heavyweight-fleece-pullover-hoodie": P.hoodieBlack,
  "classic-midweight-fleece-hoodie": P.hoodie,
  "full-zip-fleece-hoodie": P.hoodieZip,
  "french-terry-pullover-hoodie": P.hoodieFrenchTerry,
  "oversized-boxy-streetwear-hoodie": P.hoodieOversized,
  "cropped-fleece-hoodie": P.hoodieCropped,
  "performance-tech-fleece-hoodie": P.hoodieTech,
  "organic-cotton-eco-hoodie": P.hoodieFrenchTerry,
  "waterproof-windbreaker": P.windbreaker,
  "colorblock-team-hoodie": P.hoodieZip,
  "mustard-campus-hoodie": P.hoodieOversized,
  "royal-blue-athleisure-hoodie": P.hoodieZip,
  "plus-size-fleece-hoodie": P.hoodieBlack,
  "minimal-logo-hoodie": P.hoodie,
  "sherpa-lined-hoodie": P.hoodieBlack,
  "tie-dye-festival-hoodie": P.hoodieOversized,
  "camo-print-hoodie": P.hoodieBlack,
  "quarter-zip-fleece-hoodie": P.hoodieZip,
  "pullover-hoodie-with-side-zip": P.hoodieZip,
  "reflective-safety-hoodie": P.hoodieBlack,
  "fleece-hoodie-with-thumbholes": P.hoodie,
  "lightweight-summer-hoodie": P.hoodieFrenchTerry,
  "premium-brushed-fleece-hoodie": P.hoodieBlack,
  "raw-hem-street-hoodie": P.hoodieCropped,
  "embroidery-panel-hoodie": P.hoodie,
  "varsity-letter-hoodie": P.hoodieZip,
  "kids-youth-fleece-hoodie": P.hoodie,
  "womens-cropped-zip-hoodie": P.hoodieCropped,
  "travel-packable-hoodie": P.windbreaker,
  "workwear-fleece-hoodie": P.hoodieBlack,

  // Shorts
  "athletic-performance-shorts": P.shorts,
  "cotton-cargo-shorts": P.shortsCargo,
  "chino-walk-shorts": P.shortsChino,
  "basketball-mesh-shorts": P.shorts,
  "training-compression-shorts": P.sportsGym,
  "board-swim-shorts": P.shorts,
  "olive-utility-shorts": P.shortsCargo,
  "white-court-mesh-shorts": P.shortsChino,
  "running-split-shorts": P.sportsGym,
  "golf-flex-shorts": P.shortsChino,
  "yoga-stretch-shorts": P.sportsGym,
  "denim-cutoff-shorts": P.jeansStraight,
  "linen-blend-shorts": P.shortsChino,
  "tactical-cargo-shorts": P.shortsCargo,
  "casual-fleece-shorts": P.shorts,
  "printed-beach-shorts": P.shorts,
  "performance-7-inch-shorts": P.sportsGym,
  "5-inch-gym-shorts": P.sportsGym,
  "9-inch-basketball-shorts": P.shorts,
  "hiking-trail-shorts": P.shortsCargo,
  "workwear-utility-shorts": P.shortsCargo,
  "kids-youth-mesh-shorts": P.shorts,
  "womens-high-waist-shorts": P.shortsChino,
  "biker-compression-shorts": P.sportsGym,
  "tennis-club-shorts": P.shortsChino,
  "soccer-training-shorts": P.shorts,
  "lightweight-travel-shorts": P.shortsChino,
  "quick-dry-adventure-shorts": P.shortsCargo,
  "classic-chino-shorts": P.shortsChino,
  "premium-tailored-shorts": P.shortsChino,

  // Jeans
  "slim-fit-stretch-denim-jeans": P.jeans,
  "straight-fit-classic-jeans": P.jeansStraight,
  "relaxed-fit-work-jeans": P.jeans,
  "women-high-rise-skinny-jeans": P.jeansStraight,
  "distressed-streetwear-jeans": P.jeansStraight,
  "wide-leg-fashion-jeans": P.jeans,
  "petite-high-rise-jeans": P.jeansStraight,
  "big-tall-denim-jeans": P.jeans,
  "ecru-raw-denim-jeans": P.jeans,
  "tapered-athletic-jeans": P.jeansStraight,
  "bootcut-classic-jeans": P.jeans,
  "mom-fit-vintage-jeans": P.jeansStraight,
  "boyfriend-relaxed-jeans": P.jeans,
  "cropped-ankle-jeans": P.jeansStraight,
  "dark-wash-premium-jeans": P.jeansStraight,
  "light-wash-summer-jeans": P.jeans,
  "black-coated-denim-jeans": P.jeansStraight,
  "grey-washed-denim-jeans": P.jeansStraight,
  "ripped-knee-fashion-jeans": P.jeansStraight,
  "selvedge-raw-denim-jeans": P.jeans,
  "stretch-comfort-jeans": P.jeansStraight,
  "workwear-carpenter-jeans": P.jeans,
  "double-knee-utility-jeans": P.jeansStraight,
  "flared-retro-jeans": P.jeans,
  "jogger-denim-hybrid": P.jeansStraight,
  "high-stretch-jegging-jeans": P.jeansStraight,
  "kids-youth-denim-jeans": P.jeans,
  "uniform-work-denim-jeans": P.jeansStraight,
  "premium-japanese-denim-jeans": P.jeans,
  "eco-recycled-denim-jeans": P.jeansStraight,
};

type ImageRule = { pattern: RegExp; image: string };

/** Keyword fallback when slug is not in the exact map */
const NAME_RULES: Record<string, ImageRule[]> = {
  "1": [
    { pattern: /performance|moisture|gym|neon/i, image: P.performanceTee },
    { pattern: /oversized|street|box|camo|longline|tall/i, image: P.streetwearTee },
    { pattern: /gold|red|tie.?dye/i, image: P.teeRed },
    { pattern: /stack|striped|raglan|henley|tri-blend|vintage/i, image: P.teeStack },
  ],
  "2": [
    { pattern: /burgundy|maroon|club/i, image: P.poloBurgundy },
    { pattern: /beige|sand|resort|travel/i, image: P.poloBeige },
    { pattern: /striped|stripe|rugby/i, image: P.poloStriped },
    { pattern: /contrast/i, image: P.poloContrast },
    { pattern: /tipped|cuff/i, image: P.poloTipped },
    { pattern: /mesh|dry.?fit|performance|golf|sports/i, image: P.poloMesh },
    { pattern: /rugby/i, image: P.poloRugby },
    { pattern: /pocket/i, image: P.poloPocket },
    { pattern: /zip|thermal|long sleeve|winter/i, image: P.poloLongSleeve },
    { pattern: /colorblock|team|school|youth/i, image: P.poloColorblock },
    { pattern: /olive|eco|green/i, image: P.poloOlive },
    { pattern: /grey|gray|corporate|slim|henley|custom|embroidery/i, image: P.poloGrey },
    { pattern: /white|tennis|pearl|women|mercerized/i, image: P.poloWhite },
    { pattern: /long sleeve/i, image: P.poloLongSleeve },
  ],
  "3": [
    { pattern: /windbreaker|waterproof|packable|travel/i, image: P.windbreaker },
    { pattern: /zip|quarter/i, image: P.hoodieZip },
    { pattern: /cropped|raw hem|women/i, image: P.hoodieCropped },
    { pattern: /oversized|boxy|tie.?dye|mustard|campus/i, image: P.hoodieOversized },
    { pattern: /french terry|terry|summer|organic|lightweight/i, image: P.hoodieFrenchTerry },
    { pattern: /tech|performance|athleisure|varsity/i, image: P.hoodieTech },
    { pattern: /black|heavyweight|sherpa|camo|safety|workwear|plus/i, image: P.hoodieBlack },
  ],
  "4": [
    { pattern: /cargo|utility|tactical|hiking|adventure|olive/i, image: P.shortsCargo },
    { pattern: /chino|walk|golf|linen|tennis|tailored|travel|classic/i, image: P.shortsChino },
    { pattern: /compression|gym|yoga|training|7-inch|5-inch|biker/i, image: P.sportsGym },
    { pattern: /denim|cutoff/i, image: P.jeansStraight },
  ],
  "5": [
    { pattern: /dark|black|grey|gray|distressed|ripped|skinny|cropped|jegging|coated|premium japanese|women|petite|mom|bootcut|retro|flared/i, image: P.jeansStraight },
    { pattern: /light|ecru|raw|slim|straight|relaxed|wide|stretch|comfort|work|uniform|kids|japanese|recycled/i, image: P.jeans },
  ],
  "6": [
    { pattern: /backpack|daypack|laptop|commuter|hiking|leather backpack|anti-theft|school|roll-top/i, image: P.backpack },
    { pattern: /crossbody|sling|belt bag|gold accent/i, image: P.crossbody },
    { pattern: /duffel|gym|weekend|travel|garment|weekender/i, image: P.duffel },
    { pattern: /navy|structured mini/i, image: P.bagNavy },
  ],
  "7": [
    { pattern: /white|canvas|court|tennis/i, image: P.sneakersWhite },
    { pattern: /run|runner|red/i, image: P.sneakersRun },
    { pattern: /high.?top|basketball/i, image: P.sneakersHighTop },
    { pattern: /trail|hiking|grey|gray/i, image: P.sneakersTrail },
    { pattern: /lifestyle|black|leather/i, image: P.sneakers },
  ],
  "8": [
    { pattern: /cap|visor/i, image: P.cap },
    { pattern: /beanie|knit/i, image: P.beanie },
    { pattern: /sock/i, image: P.socks },
    { pattern: /scarf/i, image: P.scarf },
    { pattern: /belt|leather/i, image: P.accessories },
  ],
};

const CATEGORY_DEFAULT: Record<string, string> = {
  "1": P.tshirt,
  "2": P.polo,
  "3": P.hoodie,
  "4": P.shorts,
  "5": P.jeans,
  "6": P.bag,
  "7": P.sneakers,
  "8": P.accessories,
};

/** Resolve a name-accurate catalog image for a product */
export function resolveProductImage(
  name: string,
  categoryId: string,
  slug?: string
): string {
  const key = slug ?? slugify(name);
  const exact = SLUG_IMAGE_MAP[key];
  if (exact) return exact;

  const rules = NAME_RULES[categoryId] ?? [];
  for (const rule of rules) {
    if (rule.pattern.test(name)) return rule.image;
  }

  return CATEGORY_DEFAULT[categoryId] ?? IMAGES.placeholder;
}
