/**
 * Product / collection image URLs.
 * ALL catalog product images are local files under /public/images/products.
 * Unsplash is used only for hero, about, and collection banners.
 */

export function unsplash(photoId: string, width: number, quality = 80) {
  return `https://images.unsplash.com/${photoId}?auto=format&fit=crop&w=${width}&q=${quality}`;
}

const local = (file: string) => `/images/products/${file}`;

/** Local blank wholesale catalog images — product cards use these only */
const L = {
  bagToteBeige: local("bag-tote-beige.png"),
  bagToteNavy: local("bag-tote-navy.png"),
  bagBackpack: local("bag-backpack-black.png"),
  bagCrossbody: local("bag-crossbody-black.png"),
  bagDuffel: local("bag-duffel-black.png"),
  teeWhite: local("tee-white-flat.png"),
  teeBlack: local("tee-black-flat.png"),
  teeStack: local("tee-stack-basics.png"),
  teeRed: local("tee-red-performance.png"),
  poloNavy: local("polo-navy-folded.png"),
  poloWhite: local("polo-white-folded.png"),
  poloLongSleeve: local("polo-black-longsleeve.png"),
  hoodieGrey: local("hoodie-grey-flat.png"),
  hoodieZip: local("hoodie-black-zip.png"),
  hoodieBlack: local("hoodie-black-pullover.png"),
  hoodieTerry: local("hoodie-white-terry.png"),
  hoodieOversized: local("hoodie-beige-oversized.png"),
  hoodieCropped: local("hoodie-black-cropped.png"),
  windbreaker: local("jacket-navy-windbreaker.png"),
  shortsMesh: local("shorts-black-mesh.png"),
  shortsChino: local("shorts-khaki-chino.png"),
  shortsCargo: local("shorts-olive-cargo.png"),
  shortsCompression: local("shorts-black-compression.png"),
  jeansStack: local("jeans-blue-stack.png"),
  jeansDark: local("jeans-dark-wash.png"),
  shoesWhite: local("shoes-white-court.png"),
  shoesBlack: local("shoes-black-lifestyle.png"),
  shoesHighTop: local("shoes-black-hightop.png"),
  shoesRunner: local("shoes-red-runner.png"),
  shoesCanvas: local("shoes-white-canvas.png"),
  shoesTrail: local("shoes-grey-trail.png"),
  accCap: local("acc-cap-black.png"),
  accBelt: local("acc-belt-brown.png"),
  accBeanie: local("acc-beanie-navy.png"),
  accSocks: local("acc-socks-white.png"),
  accScarf: local("acc-scarf-brown.png"),
} as const;

const PHOTOS = {
  heroRetail: "photo-1441986300917-64674bd600d8",
  heroStreetwear: "photo-1552374196-1ab2a1c593e8",
  heroSports: "photo-1517836357463-d25dfeac3438",
  summerCollection: "photo-1445205170230-053b83016050",
  winterCollection: "photo-1489987707025-afc232f7ea0f",
  sportsCollection: "photo-1517836357463-d25dfeac3438",
  streetwearCollection: "photo-1552374196-1ab2a1c593e8",
  denimCollection: "photo-1542272604-787c3835535d",
  footwearCollection: "photo-1549298916-b41d501d3772",
  aboutManufacturing: "photo-1445205170230-053b83016050",
  aboutFactory: "photo-1581091226825-a6a2a5aee158",
} as const;

export const IMAGES = {
  hero: [
    { image: unsplash(PHOTOS.heroRetail, 1920), title: "Premium Fashion Export" },
    { image: unsplash(PHOTOS.heroStreetwear, 1920), title: "Global B2B Partner" },
    { image: unsplash(PHOTOS.heroSports, 1920), title: "Quality Manufacturing" },
  ],
  about: {
    manufacturing: unsplash(PHOTOS.aboutManufacturing, 800),
    factory: unsplash(PHOTOS.aboutFactory, 800),
  },
  collections: {
    summer: { banner: unsplash(PHOTOS.summerCollection, 1200), thumb: unsplash(PHOTOS.summerCollection, 400) },
    winter: { banner: unsplash(PHOTOS.winterCollection, 1200), thumb: unsplash(PHOTOS.winterCollection, 400) },
    sports: { banner: unsplash(PHOTOS.sportsCollection, 1200), thumb: unsplash(PHOTOS.sportsCollection, 400) },
    streetwear: { banner: unsplash(PHOTOS.streetwearCollection, 1200), thumb: unsplash(PHOTOS.streetwearCollection, 400) },
    denim: { banner: unsplash(PHOTOS.denimCollection, 1200), thumb: unsplash(PHOTOS.denimCollection, 400) },
    footwear: { banner: unsplash(PHOTOS.footwearCollection, 1200), thumb: unsplash(PHOTOS.footwearCollection, 400) },
  },
  /** Every key is a local /images/products/*.png — no Unsplash in product cards */
  products: {
    bag: L.bagToteBeige,
    bagNavy: L.bagToteNavy,
    backpack: L.bagBackpack,
    crossbody: L.bagCrossbody,
    duffel: L.bagDuffel,
    tshirt: L.teeWhite,
    teeStack: L.teeStack,
    teeRed: L.teeRed,
    streetwearTee: L.teeBlack,
    performanceTee: L.teeRed,
    vneckTee: L.teeWhite,
    polo: L.poloNavy,
    poloWhite: L.poloWhite,
    poloPerformance: L.poloWhite,
    poloLongSleeve: L.poloLongSleeve,
    hoodie: L.hoodieGrey,
    hoodieZip: L.hoodieZip,
    hoodieBlack: L.hoodieBlack,
    hoodieFrenchTerry: L.hoodieTerry,
    hoodieOversized: L.hoodieOversized,
    hoodieCropped: L.hoodieCropped,
    hoodieTech: L.hoodieZip,
    windbreaker: L.windbreaker,
    shorts: L.shortsMesh,
    shortsCargo: L.shortsCargo,
    shortsChino: L.shortsChino,
    shortsBasketball: L.shortsMesh,
    sportsGym: L.shortsCompression,
    sportsYoga: L.shortsCompression,
    sportsRun: L.shoesRunner,
    jeans: L.jeansStack,
    jeansStraight: L.jeansDark,
    jeansRelaxed: L.jeansStack,
    jeansWomen: L.jeansDark,
    sneakers: L.shoesBlack,
    sneakersRun: L.shoesRunner,
    sneakersWhite: L.shoesWhite,
    sneakersHighTop: L.shoesHighTop,
    sneakersCanvas: L.shoesCanvas,
    sneakersTrail: L.shoesTrail,
    sneakersLifestyle: L.shoesBlack,
    accessories: L.accBelt,
    cap: L.accCap,
    beanie: L.accBeanie,
    socks: L.accSocks,
    scarf: L.accScarf,
  },
  placeholder: "/images/placeholder.svg",
} as const;
